steps:
  - name: golang
    args: ['go', 'version']
  - name: golang
    args: ['go', 'test']
    dir: ''
  - name: 'gcr.io/cloud-builders/gcloud'
    # figure out how to handle env variables
    args: ['functions', 'deploy', 'sleepyhead', '--trigger-event', 'google.pubsub.topic.publish', '--trigger-resource', 'catears', '--runtime', 'go116', '--entry-point', 'HiSleepyHead']
    dir: ''